export const REQUEST_UPDATE_DAYS = "REQUEST_UPDATE_DAYS";
export const SUCCESS_UPDATE_DAYS = "SUCCESS_UPDATE_DAYS";
export const ERROR_UPDATE_DAYS = "ERROR_UPDATE_DAYS";
export const REQUEST_MANAGE_PINNED_COLS = "REQUEST_MANAGE_PINNED_COLS";
export const SUCCESS_MANAGE_PINNED_COLS = "SUCCESS_MANAGE_PINNED_COLS";
